### ISSUE TITLE
StarChart.json contains trailing commas

### ISSUE THREAD

**Issue by robotboy655** [VoiDGlitch/WarframeData#11]
https://github.com/VoiDGlitch/WarframeData/blob/master/StarChart.json#L12

This should not be there, otherwise JSON.parse fails.

**Comment by robotboy655** [comment]
Looking even further and it seems that StarChart.json doesn't even contain all the nodes, things like Draco on Ceres, etc, also max and minimum levels are missing ( And I know there are defined from where you are getting your data )

**Comment by Chuanhsing** [comment]
It's missing NT_CLAN nodes.

**Comment by macdja38** [comment]
@robotboy655 Fixed in https://github.com/VoiDGlitch/WarframeData/commit/54ed22eb384fa1212201fcd0c9642f38973806ea
