### ISSUE TITLE
LootItems mapping

### ISSUE THREAD

**Issue by loootsforus** [VoiDGlitch/WarframeData#12]
Would it be possible to get a reward table mapping?

for example:
/Lotus/StoreItems/Types/Recipes/Weapons/JawBlueprint = Jaw Blueprint
/Lotus/StoreItems/Upgrades/Mods/Warframe/DualStat/RunSpeedArmorMod =  Armored Agility

**Comment by VoiDGlitch** [comment]
Honestly, I don't feel like taking the time to keep track of that type of
data set.

**Comment by loootsforus** [comment]
no problem just wanted to check.
