### ISSUE TITLE
MissionDecks.txt displays all rewards as empty string

### ISSUE THREAD

**Issue by PhantomOfAres** [VoiDGlitch/WarframeData#13]
Seems like something went wrong with the formatting of MissionDecks.txt since update 19. The human-readable names seem to all be "" (ie 1 "", COMMON, 10.84%).

**Comment by sctjkc01** [comment]
Oddly enough, I think this might be because there are no files kept client-side anymore except for graphical stuff.  I was looking through my personal install, and saw nothing but animations, emblems, fonts, textures... and sounds, from the looks of Misc.  I don't think any of the MissionDeck stuff is kept clientside anymore.

**Comment by PhantomOfAres** [comment]
Yeah, that was my worry too. The interesting thing is that there drop chances are still there, so maybe it's a change in format rather than moving them server side, but I haven't looked, and don't have any particular expertise in hunting such things down.

**Comment by rexed123** [comment]
I think that only tables with "Stripped=True" note are kept server-side and the rest may indeed have gotten a format change. I checked one other warframe datamine source and this issue isn't resolved there either.

**Comment by VoiDGlitch** [comment]
PhantomOfAres, it seems like the localization path to each entity in MissionDecks.txt has been relocated to a different path or that there was a format change in the file. Will look into it with a friend when time allows us to. 

sctjkc01, you will not see MissionDecks.txt in your base install of WARFRAME. You can only retrieve it through extracting it from the application itself.

rexed123, yes, any MissionDeck that returns "Stripped=True" is server-side. Also, do you mind linking me this other WARFRAME data source?

**Comment by rexed123** [comment]
I have no idea whether whoever runs this site just rearragndes data from this depo or do extacts it on their own but here it is http://wf.poedb.tw/us/

**Comment by VoiDGlitch** [comment]
rexed123, the person that runs that website uses data from my repository to manage it and he does a little extracting of his own.

All, currently investigating the issue still.
