### ISSUE TITLE
Playtests not going according to the information

### ISSUE THREAD

**Issue by Gamator** [VoiDGlitch/WarframeData#15]
Hi. I was trying to get some relics and got different drops than the ones on the list. I did Kala-azar(Eris) and got a Neo on Rotation B, then did Valefor(Europa) and got a 2000 credit bundle on Rotation B. Don't know how datamining works so i figured i should ask you personally what can you make out of this.
Thanks for your time 👍

**Comment by rexed123** [comment]
It's not a problem with data you found here it's probably that you don't understand how rotations work so let me explain it. Endless missions are played in intervals (in survival interval is every 5 minutes, interception it's one round and so on). You get a reward every interval but they are given in "AABC and repeat". That means that you get something rolled from same rotation first two times then B, then C and then cycle resets so you get A twice again. #15 up to closing I'd guess.

**Comment by VoiDGlitch** [comment]
Yeah, since you (Gamator) did not provide any evidence to your problem, I can only assume (rexed123) has the answer to your issue.

**Comment by Gamator** [comment]
Well it appears that i've been wrong this entire time then. I always believed it was ABBC and so far every single mission had been proving this right. If it trully is AABC then the issue is solved.
