### ISSUE TITLE
Warframe realtime package parsing

### ISSUE THREAD

**Issue by Lunat1q** [VoiDGlitch/WarframeData#16]
Greetings! (Sorry for opening Issue)
I'm currently trying to develop warframe parser (mainly for chat/trading) but who knows the limit :)
Do you have any experience of parsing sniffered packages from the network stream?
So far as i see it's sort of JSON + something else, also it's encrypted/encoded somehow, can't get it, so may be you want to help.

**Comment by hennekey** [comment]
@Lunat1q Did you read the Terms of Service to see if this is a violation? Sometimes this behavior is frowned upon and can result in bans.

**Comment by Lunat1q** [comment]
Ofc i read it :)
So far - i have no problems sniffing data.
Since it's about undetectable.
Atm i can read byted data, dump it, attempt to translate it to dictionary/object, but data is not full, also some part is crypted.

**Comment by VoiDGlitch** [comment]
Apologies, but I cannot assist in your affairs.
