### ISSUE TITLE
another parsing error?

### ISSUE THREAD

**Issue by tuttomax** [VoiDGlitch/WarframeData#18]
"Locations": [
"Neptune, THE INDEX": "ENDURANCE, MT_ARENA, FC_CORPUS, NT_SUB_MISSION"
...
]
when usually is like this 
"Locations": [
"Eris, Candiru, MT_HIVE, FC_INFESTATION, NT_EVENT",
...
]

**Comment by VoiDGlitch** [comment]
Notified the person who works on this portion of the repository.
