### ISSUE TITLE
include item name conversions in languages.json

### ISSUE THREAD

**Issue by aliasfalse** [VoiDGlitch/WarframeData#2]

**Comment by macdja38** [comment]
could you please explain what you are looking for? possibly with an example?

**Comment by aliasfalse** [comment]
```json
{
    "/Lotus/StoreItems/Weapons/Tenno/Melee/Fist/Fist" : {
        "value" : "Item name"
    }
}

**Comment by macdja38** [comment]
ohh, you mena like:
```json
{  "/lotus/language/items/fistname": {
    "value": "FURAX"
  }
}```
I think we already do that?

**Comment by aliasfalse** [comment]
no, i definitely mean with `/lotus/storeitems/...`

**Comment by aliasfalse** [comment]
storeitems have to be converted to equivalent display strings

**Comment by macdja38** [comment]
umm... ok... I don't believe we have that at the moment. @VoiDGlitch may know more.

**Comment by VoiDGlitch** [comment]
StoreItems = Assets
Language = Localization

A StoreItem will always have localization assigned to it, but it will never be the direct localization string. Because of this, obtaining the format you are looking for is impossible.

**Comment by aliasfalse** [comment]
we shall see how it goes from a different approach, then
