### ISSUE TITLE
same parsing error

### ISSUE THREAD

**Issue by tuttomax** [VoiDGlitch/WarframeData#22]
on JSON line 284 

"Neptune: The Index","..."

**Comment by macdja38** [comment]
in... what file? maybe provide a link to the line if possible.

**Comment by tuttomax** [comment]
yeah 
https://github.com/VoiDGlitch/WarframeData/blob/master/JSON/MissionDecks.json#L289
also 305

should be like this (in 274)
"Locations": [
      "Neptune, THE INDEX, MT_ARENA, FC_CORPUS, NT_EVENT"
],

instead it's 
"Locations" : [
{
 "..." : " ... "
}
]

**Comment by macdja38** [comment]
Regrettably I'm not familiar enough with yaml to know why it's translating the lists into objects if they have one entry and arrays if they have multiple, I'll look into it in the next few days.

**Comment by tuttomax** [comment]
sure, probably i will work at the project in holiday so there's no hurry
