### ISSUE TITLE
Star chart Earth is now [PH]

### ISSUE THREAD

**Issue by SirCumz** [VoiDGlitch/WarframeData#23]
All Earth nodes got a [PH] as Planet name instead of Earth

**Comment by SirCumz** [comment]
As far as i can see the star chart parser regex is wrong, instead of [Earth] it matches the first [PH] excavation node..

**Comment by macdja38** [comment]
Chances are you are correct, if you would like to support a pr with a corrected parser I will test and merge it, if not I'll try and get around to it but no promises on soon.

**Comment by SirCumz** [comment]
Created a PR. It should be fixed now.
