### ISSUE TITLE
Feature request - colors

### ISSUE THREAD

**Issue by rubbl3** [VoiDGlitch/WarframeData#5]
Hey, sorry to be a bother but I figured it'd be worth asking.

You know how you show the hexcodes for colors on kubrow and kavat pages? Would it be possible to do something similar for all the other equipment in the game that's colorable?

I realize it would be a pretty huge undertaking because between all the color palettes, frames, weapons and various cosmetics there is just so much at this point but if it's possible to pull that information from the game and there is some reasonable way to automate it, please consider making this information available.
I (and I'm sure many others considering how people love to go on about their fashionframe) would really appreciate it. Thanks a lot!

**Comment by VoiDGlitch** [comment]
This would not really be possible, because there is a difference between defining a color and defining the colors of an item. You cannot clearly tell the latter. It is possible with a color alone, because it is simply a color.

**Comment by rubbl3** [comment]
Ohh, I'm a dumbass, sorry about that. Should have been more specific.

What I meant were the _default_ colors and the color palettes so that we could compare between them. Like let's say checking the color scheme of your favorite weapon and using it on other weapons or to see if there are any differences in prime golds.

As far as I understand it, the textures the game uses are black and white and the default colors are applied the same way that we customize our equipment, it's just not visible to the player (because it's possible to keep a frame at default colors, then copy the main colors onto an armor piece or something and then you CAN see the default colors and even check them against the available palettes).

To be super specific, that was actually why I asked in the first place. I wanted to know the orange on harkonar armor so that I could coordinate a frame and some grineer weapons to it. Of course I can just try and look for a similar color myself but if I could find the perfect shade or the closest possible match with your help, then all the better.

Anyway, if I'm still not understanding it correctly and it's really not possible, then feel free to close this. Thanks for the response!

**Comment by VoiDGlitch** [comment]
Oh, I think you are asking about retrieving the colors in the color palettes? I'm not sure if that is possible or not.

**Comment by rubbl3** [comment]
Yep, those. Presumably the stuff that applies as defaults onto equipment would be in the same or similar place.

Don't worry about it too much but if you ever come across it or figure it out, it would be awesome.
