### ISSUE TITLE
Data used in EE.cfg file at %appdata%\local\warframe

### ISSUE THREAD

**Issue by HoDANG** [VoiDGlitch/WarframeData#7]
**Is it possible for you to get the values that are used inside of the EE.cfg file?**

*note: Only edit EE.cfg while the game is closed.*

Using the `Languages.json` file, I've been able to figure out some of the values Warframe uses for keybindings. You can do the same by using Ctrl+F(Find) in your browser, then type in `/lotus/language/menu/input_` . You should find 72 results, where the text after `input_` will be your `key=` value in the EE.cfg . You can find actual keybinding names by typing in either a `<` or a `>` , then scrolling through till you find one that looks promising. That's how I've found `<LOOK_X>` and `<LOOK_Y>` (read on below)

I've figured out that you can use keyboard buttons to control the camera by assigning keys to the values LOOK_X and LOOK_Y. Each axis needs two keybindings. One with invert=0, and the other with invert=1. So it will be 4 keybindings in total. 

For example, if you enter this into your EE.cfg file, it will bind your arrow pad on your keyboard to control the camera. However, there is something that makes editing the EE.cfg difficult... 

```
+nowarning
+version=5

[KeyBindings,/EE/Types/Input/KeyBindings]

[LotusWindows_KeyBindings,/Lotus/Types/Input/KeyBindings]
LOOK_X={
    {
        key=EN_LEFT
        inputMode=IM_NORMAL
        invert=1
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    },
    {
        key=EN_RIGHT
        inputMode=IM_NORMAL
        invert=0
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    }
}
LOOK_Y={
    {
        key=EN_UP
        inputMode=IM_NORMAL
        invert=1
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    },
    {
        key=EN_DOWN
        inputMode=IM_NORMAL
        invert=0
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    }
}
```

The annoying part about EE.cfg is that it only fills up with values that have been changed from their defaults.

For example, if you open up Warframe after freshly installing it, and close Warframe, EE.cfg will **not** contain keybindings.

However, if you open up Warframe, change your HOLD_CROUCH keybinding to H, and then close Warframe, now HOLD_CROUCH will appear inside of EE.cfg. 

If you haven't figured out what I'm saying yet, it is that you are unable to change your camera bindings without losing camera functionality from the mouse. 

This is because the `key=` for mouse movement is unknown, and there is no option to change the camera keybindings in game, so we cannot change it from default in order for it to show up inside of EE.cfg. 

This is why I'm wondering if you can extract the list of possible values that can be inputted into this EE.cfg file. We could possibly change our FOV higher than the max value in game, because this file also stores graphics settings. 

Tysm for the great information. It has proven to be helpful to me while I've been playing, and I've had a lot of fun messing with things in the EE.cfg file. If only we can take it further c:

**Comment by HoDANG** [comment]
I have figured out how to use mouse movements.

You use a `key=` of `EN_MOUSE_X` and `EN_MOUSE_Y`

So now the example would be changed to this. 

```
+nowarning
+version=5

[KeyBindings,/EE/Types/Input/KeyBindings]

[LotusWindows_KeyBindings,/Lotus/Types/Input/KeyBindings]
LOOK_X={
    {
        key=EN_LEFT
        inputMode=IM_NORMAL
        invert=1
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    },
    {
        key=EN_RIGHT
        inputMode=IM_NORMAL
        invert=0
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    },
    {
        key=EN_MOUSE_X
        inputMode=IM_NORMAL
        invert=0
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    }
}
LOOK_Y={
    {
        key=EN_UP
        inputMode=IM_NORMAL
        invert=1
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    },
    {
        key=EN_DOWN
        inputMode=IM_NORMAL
        invert=0
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    },
    {
        key=EN_MOUSE_Y
        inputMode=IM_NORMAL
        invert=0
        deadzone=0
        scale=1
        povAxis=PAT_UNUSED
        inputFilter=""
        strictFiltering=0
    }
}
```
However, by doing this, the sensitivity of the mouse seems to screw up. It stops being affected by the in game sensitivity setting. 

This is not the case for the NESW arrows, which seem to adapt to the in game sensitivity setting as expected.

I have been experimenting with the `scale=` value, but I can't tell weather it has any effect. Maybe I am not using the right number? I've also tried changing the `deadzone=` value, but that screwed things up even worse.

Maybe there are more options such as `EN_MOUSE_Y+` and `EN_MOUSE_Y-` which I have no yet discovered.

It still would be nice to know what else EE.cfg can do.

**Comment by VoiDGlitch** [comment]
Personally, I do not know anything about the EE.cfg file, so I cannot help you with your issue.
