### ISSUE TITLE
Russian Languages.bin

### ISSUE THREAD

**Issue by BlackSiriuS** [VoiDGlitch/WarframeData#9]
Prompt how to unpack Languages.bin for the Russian language? Why then PackagesLexer is not unpack, probably out of date.

**Comment by Chuanhsing** [comment]
PackagesLexer is another's project.

**Comment by VoiDGlitch** [comment]
What?

**Comment by Chuanhsing** [comment]
He said 'Why then PackagesLexer is not unpack, probably out of date.' PackagesLexer is  Deathmax's project. https://github.com/Deathmax/WFPackageParser

BTW, I don't think you will provide other languages.

**Comment by VoiDGlitch** [comment]
Yeah, I'm not branching outside of en.
